system_id: 'rr39261'
company_id: 'RDS11'
user_id: 'Web.Service'
account_password: 'LoyaltyAPI1'
system_password: '!069158823A'
wsdl_url: 'https://memberlinkWS.alohaenterprise.com/insightws/MemberLinkWS?wsdl'

